/**
 * Connect Marketplace Use Case
 * 
 * Application layer use case for connecting to a marketplace.
 * 
 * Architecture:
 * - Orchestrates marketplace adapter and repository calls
 * - Handles connection workflow
 * - Returns connection result
 * - Uses AdapterExecutor for robust adapter execution
 * 
 * Transaction Boundary:
 * - Adapter calls are OUTSIDE UnitOfWork transactions
 * - DB writes remain inside UnitOfWork
 * - This prevents adapter timeouts from blocking database transactions
 */

import { IMarketplaceConnectionRepository } from '../../../repositories/marketplace-connection.repository.interface.js';
import { MarketplaceAdapter } from '../../../contracts/marketplace.contract.js';
import { MarketplaceConnection, MarketplaceType, IntegrationStatus } from '../../../domain/entities/marketplace-connection.entity.js';
import { CompanyId } from '../../../domain/value-objects/ids.vo.js';
import { AdapterExecutor, defaultRetryPolicy, createAdapterContext } from '../../../infrastructure/adapters/runtime/index.js';
import { UnitOfWork } from '../../../infrastructure/unit-of-work/index.js';
import { mapAdapterErrorToDomainError } from './adapter-error-mapper.js';
import { IntegrationDisabledError } from '../../../errors/integration-disabled.error.js';
import { env } from '../../../config/env.js';

export interface ConnectMarketplaceInput {
  companyId: string;
  type: MarketplaceType;
  name: string;
  apiUrl?: string;
  apiKey?: string;
  apiSecret?: string;
  sellerId?: string;
  accessToken?: string;
  refreshToken?: string;
  settings?: Record<string, unknown>;
  syncMode?: string;
  isReadOnly?: boolean;
}

export interface ConnectMarketplaceOutput {
  connection: MarketplaceConnection;
  testResult: { success: boolean; message?: string };
}

export class ConnectMarketplaceUseCase {
  constructor(
    private readonly marketplaceConnectionRepository: IMarketplaceConnectionRepository,
    private readonly marketplaceAdapter: MarketplaceAdapter,
    private readonly unitOfWork: UnitOfWork
  ) {}

  async execute(input: ConnectMarketplaceInput): Promise<ConnectMarketplaceOutput> {
    // v3.1 HARD RESET: Disable marketplace connections
    if (env.INTEGRATIONS_DISABLED) {
      throw new IntegrationDisabledError();
    }

    // TODO: Add validation

    // Check if connection already exists (read operation, no transaction needed)
    const existing = await this.marketplaceConnectionRepository.findByTypeAndCompany(
      input.type,
      input.companyId
    );

    if (existing) {
      throw new Error(`Marketplace connection already exists for type: ${input.type}`);
    }

    // Prepare credentials for adapter context
    const credentials = {
      apiUrl: input.apiUrl,
      apiKey: input.apiKey,
      apiSecret: input.apiSecret,
      sellerId: input.sellerId,
      accessToken: input.accessToken,
      refreshToken: input.refreshToken,
    };

    // Create adapter context (using temporary integrationId, will be updated after creation)
    const context = createAdapterContext(
      input.type,
      input.companyId,
      'temp', // Temporary ID, will be replaced after connection creation
      credentials,
      {
        ...(input.settings || {}),
        syncMode: input.syncMode ?? 'AUTO',
        isReadOnly: input.isReadOnly ?? false,
      }
    );

    // Create adapter executor with retry policy
    const executor = new AdapterExecutor(defaultRetryPolicy, context);

    // ============================================================
    // TRANSACTION BOUNDARY: Adapter calls are OUTSIDE transactions
    // ============================================================
    // Test connection via executor (with retry logic)
    // This call is OUTSIDE any database transaction to prevent
    // adapter timeouts from blocking database transactions
    let testResult = { success: false, message: '' };
    try {
      await executor.testConnection(this.marketplaceAdapter);
      testResult = { success: true };
    } catch (error) {
      // Map adapter errors to domain errors
      const domainError = mapAdapterErrorToDomainError(error);
      testResult = {
        success: false,
        message: domainError.message,
      };
      // TODO: Decide if we should create connection even if test fails
    }

    // ============================================================
    // TRANSACTION BOUNDARY: Database writes are INSIDE transaction
    // ============================================================
    // All database write operations are wrapped in a transaction
    // to ensure atomicity and consistency
    return await this.unitOfWork.withTransaction(async (tx) => {
      // Create marketplace connection using transactional repository
      const connection = new MarketplaceConnection({
        id: '', // Will be generated by repository
        companyId: input.companyId,
        type: input.type,
        name: input.name,
        status: testResult.success ? 'ACTIVE' : 'INACTIVE',
        settings: {
          ...(input.settings || {}),
          syncMode: input.syncMode ?? 'AUTO',
          isReadOnly: input.isReadOnly ?? false,
          apiUrl: input.apiUrl,
          apiKey: input.apiKey,
          apiSecret: input.apiSecret,
          sellerId: input.sellerId,
          accessToken: input.accessToken,
          refreshToken: input.refreshToken,
        },
        lastSyncAt: null,
        syncMode: input.syncMode ?? 'AUTO',
        isReadOnly: input.isReadOnly ?? false,
      });

      const created = await tx.marketplaceConnectionRepository.create(connection);

      return { connection: created, testResult };
    });
  }
}

