/**
 * Create Order Use Case
 * 
 * Application layer use case for creating a new order.
 * 
 * Architecture:
 * - Orchestrates repository calls
 * - Validates business rules
 * - Returns domain entities
 * - No infrastructure dependencies
 */

import { IOrderRepository } from '../../../repositories/order.repository.interface.js';
import { Order, OrderStatus } from '../../../domain/entities/order.entity.js';
import { OrderItem } from '../../../domain/entities/order-item.entity.js';
import { CompanyId } from '../../../domain/value-objects/ids.vo.js';

export interface CreateOrderItemInput {
  productId: string;
  variantId?: string | null;
  sku: string;
  name: string;
  quantity: number;
  unitPrice: number;
  taxRate?: number;
  discount?: number;
  total: number;
}

export interface CreateOrderInput {
  orderNumber: string;
  marketplaceOrderId?: string;
  status?: OrderStatus;
  customerName: string;
  customerEmail?: string;
  customerPhone?: string;
  shippingAddress: string;
  shippingCity?: string;
  shippingDistrict?: string;
  shippingPostalCode?: string;
  billingAddress?: string;
  subtotal: number;
  taxAmount?: number;
  shippingCost?: number;
  discount?: number;
  total: number;
  customerNote?: string;
  integrationId?: string;
  warehouseId?: string;
  companyId: string;
  createdById?: string;
  items: CreateOrderItemInput[];
}

export interface CreateOrderOutput {
  order: Order;
}

export class CreateOrderUseCase {
  constructor(
    private readonly orderRepository: IOrderRepository
  ) {}

  async execute(input: CreateOrderInput): Promise<CreateOrderOutput> {
    // TODO: Add validation (required fields, order total calculation)
    // TODO: Add business rule checks (minimum order value, etc.)
    // TODO: Add transaction support
    // TODO: Validate order items

    // Create domain entities
    const order = new Order({
      id: '', // Will be generated by repository
      orderNumber: input.orderNumber,
      marketplaceOrderId: input.marketplaceOrderId,
      status: input.status ?? 'PENDING',
      customerName: input.customerName,
      customerEmail: input.customerEmail,
      customerPhone: input.customerPhone,
      shippingAddress: input.shippingAddress,
      shippingCity: input.shippingCity,
      shippingDistrict: input.shippingDistrict,
      shippingPostalCode: input.shippingPostalCode,
      billingAddress: input.billingAddress,
      subtotal: input.subtotal,
      taxAmount: input.taxAmount ?? 0,
      shippingCost: input.shippingCost ?? 0,
      discount: input.discount ?? 0,
      total: input.total,
      customerNote: input.customerNote,
      integrationId: input.integrationId,
      warehouseId: input.warehouseId,
      companyId: input.companyId,
      createdById: input.createdById,
      items: [],
    });

    const orderItems = input.items.map(item =>
      new OrderItem({
        id: '', // Will be generated by repository
        orderId: '', // Will be set after order creation
        productId: item.productId,
        variantId: item.variantId,
        sku: item.sku,
        name: item.name,
        quantity: item.quantity,
        unitPrice: item.unitPrice,
        taxRate: item.taxRate ?? 0,
        discount: item.discount ?? 0,
        total: item.total,
      })
    );

    // Persist via repository
    const created = await this.orderRepository.create(order, orderItems);

    return { order: created };
  }
}

