/**
 * Create Product Use Case
 * 
 * Application layer use case for creating a new product.
 * 
 * Architecture:
 * - Orchestrates repository calls
 * - Validates business rules
 * - Returns domain entities
 * - No infrastructure dependencies
 */

import { IProductRepository } from '../../../repositories/product.repository.interface.js';
import { Product } from '../../../domain/entities/product.entity.js';
import { SKU, CompanyId } from '../../../domain/value-objects/ids.vo.js';

export interface CreateProductInput {
  sku: string;
  name: string;
  price: number;
  companyId: string;
  barcode?: string | null;
  gtin?: string | null;
  description?: string | null;
  brand?: string | null;
  costPrice?: number | null;
  taxRate?: number;
  weight?: number | null;
  width?: number | null;
  height?: number | null;
  depth?: number | null;
  imageUrl?: string | null;
  isActive?: boolean;
  categoryId?: string | null;
  type?: string;
  campaignSetId?: string | null;
  minQuantity?: number;
}

export interface CreateProductOutput {
  product: Product;
}

export class CreateProductUseCase {
  constructor(
    private readonly productRepository: IProductRepository
  ) {}

  async execute(input: CreateProductInput): Promise<CreateProductOutput> {
    // TODO: Add validation (SKU uniqueness, required fields)
    // TODO: Add business rule checks
    // TODO: Add transaction support

    // Check if SKU already exists
    const exists = await this.productRepository.existsBySku(
      input.companyId,
      input.sku
    );

    if (exists) {
      throw new Error(`Product with SKU ${input.sku} already exists`);
    }

    // Create domain entity
    const product = new Product({
      id: '', // Will be generated by repository
      sku: input.sku,
      name: input.name,
      price: input.price,
      companyId: input.companyId,
      barcode: input.barcode,
      gtin: input.gtin,
      description: input.description,
      brand: input.brand,
      costPrice: input.costPrice,
      taxRate: input.taxRate ?? 20,
      weight: input.weight,
      width: input.width,
      height: input.height,
      depth: input.depth,
      imageUrl: input.imageUrl,
      isActive: input.isActive ?? true,
      categoryId: input.categoryId,
      type: input.type ?? 'PRODUCT', // TODO: Map to ProductType enum properly
      campaignSetId: input.campaignSetId,
      minQuantity: input.minQuantity ?? 0, // TODO: Use Quantity value object
    });

    // Persist via repository
    const created = await this.productRepository.create(product);

    return { product: created };
  }
}

